#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################

homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
  
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.1.1.0/24
        - 127.0.0.1
      allow_bypass_login: true
    - type: homeassistant

#################################################################
#                                                               #
#                        Customizations                         #
#                                                               #
#################################################################

frontend:
  javascript_version: latest
  themes: !include includes/themes.yaml
  # extra_html_url:
  #   - /local/fontawesome/hass-fontawesome-light.html

#################################################################
#                                                               #
#                           Enables                             #
#                                                               #
#################################################################

config:

http:

discovery:
  ignore:
    - sonos
    - netgear_router
    - samsung_tv
    - igd

conversation:

#map:

history:

logbook:

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

updater:
  include_used_components: true

####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

switch: !include includes/switches.yaml

####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################

logger:
  default: info
  #logs:
  #  homeassistant.components.mqtt: debug
  #  homeassistant.components.media_player: debug
  #  homeassistant.components.switch: debug
  #  homeassistant.components.xiaomi_aqara: info
  #  homeassistant.components.light: debug
  #  homeassistant.components.discovery: info
    
####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################

mqtt:
  broker: !secret mqtt_broker_host
  port: !secret mqtt_broker_port
  client_id: home-homeassistant
  keepalive: 60
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

#################################################################
#                                                               #
#                            Panel                              #
#                                                               #
#################################################################
    
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url:  !secret configurator_url
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url:  !secret pihole_url

####################################################
#                                                  #
#                     Recorder                     #
#                                                  #
####################################################

recorder:
  db_url: !secret db_mysql
  purge_keep_days: 5
  exclude:
    # domains:
    #   - automation
    #   - weblink
    #   - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.since_last_boot
      - sensor.ha_uptime
      - sensor.date     
      - sensor.time
      - sensor.maceio_time
      - sensor.german_time
      - sensor.date_time
      - sensor.internet_time
      - sensor.time_date
      - sensor.time_utc 