views:
  - icon: 'mdi:home'
    background: center / cover no-repeat url("/local/lovelace/background.gif") fixed
    title: Home
    path: default_view
    badges: []
    cards:
      - clock_format: '12'
        notifications: clock
        main_config: true
        clock_date: true
        voice: hide
        type: 'custom:compact-custom-header'
      - type: horizontal-stack
        cards:
          - card:
              elements:
                - style:
                    left: 30%
                    top: 90%
                    color: white
                  entity: sensor.saulo
                  type: state-label
                  prefix: 'Saulo -- '
                - style:
                    left: 47%
                    top: 10%
                    color: white
                  entity: binary_sensor.saulos_headset_ble_status
                  type: state-icon
                - style:
                    left: 63%
                    top: 10%
                    color: white
                  entity: binary_sensor.saulos_mac_ble_status
                  type: state-icon
                - style:
                    left: 77%
                    top: 10%
                    color: white
                  entity: binary_sensor.saulos_amazfit2_ble_status
                  type: state-icon
                - style:
                    left: 90%
                    top: 10%
                    color: white
                  entity: binary_sensor.saulos_pixel2xl_ble_status
                  type: state-icon
              type: picture-elements
              image: /local/lovelace/home/saulo.jpg
            type: 'custom:card-modder'
            style:
              border: 'solid 1px rgba(100,100,100,0.3)'
              border-radius: 20px
              overflow: hidden
          - card:
              elements:
                - style:
                    left: 27%
                    top: 89%
                    color: white
                  entity: sensor.olga
                  type: state-label
                  prefix: 'Olga -- '
                - style:
                    left: 90%
                    top: 10%
                    color: white
                  entity: binary_sensor.olgas_pixel2xl_ble_status
                  type: state-icon
              type: picture-elements
              image: /local/lovelace/home/olga.jpg
            type: 'custom:card-modder'
            style:
              border: 'solid 1px rgba(100,100,100,0.3)'
              border-radius: 20px
              overflow: hidden
      - card:
          elements:
            - style:
                left: 8%
                top: 88%
                color: white
              entity: binary_sensor.house_alarm_sensor
              type: state-icon
            - style:
                left: 16%
                top: 88%
                color: white
              entity: binary_sensor.doors
              type: state-icon
            - style:
                left: 32%
                top: 88%
                color: white
              entity: binary_sensor.trash
              type: state-icon
            - style:
                left: 41%
                top: 88%
                color: white
              entity: binary_sensor.recycle
              type: state-icon
            - style:
                left: 87%
                top: 82%
                color: white
              entity: sensor.temperature_158d000170e3ef
              type: state-icon
              tap_action: more-info
            - style:
                left: 87%
                top: 95%
                color: white
              entity: sensor.temperature_158d000170e3ef
              type: state-label
            - style:
                left: 9%
                top: 12%
                color: white
              entity: sensor.temperature_158d000170e48e
              type: state-label
          type: picture-elements
          image: /local/lovelace/home/home.png
        type: 'custom:card-modder'
        style:
          border: 'solid 1px rgba(100,100,100,0.3)'
          border-radius: 20px
          overflow: hidden
      - type: entities
        entities:
          - hide:
              power: true
              volume: true
            info: short
            source: icon
            group: true
            type: 'custom:mini-media-player'
            entity: media_player.home_group
          - icon: 'mdi:speaker'
            hide:
              controls: true
            show_source: true
            group: true
            artwork: cover
            artwork_border: true
            entity: media_player.samsung_tv
            type: 'custom:mini-media-player'
          - icon: 'mdi:speaker'
            hide:
              controls: true
            show_source: true
            group: true
            artwork: cover
            artwork_border: false
            entity: media_player.living_room
            type: 'custom:mini-media-player'
          - icon: 'mdi:speaker'
            hide:
              controls: true
            group: true
            artwork: cover
            artwork_border: false
            entity: media_player.family_room_speaker
            type: 'custom:mini-media-player'
      - entity: weather.dark_sky
        type: weather-forecast
  - icon: 'mdi:television'
    background: center / cover no-repeat url("/local/lovelace/background.gif") fixed
    badges: []
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
      - entities:
          - input_select.radio_station
          - input_select.media_player
          - input_number.radio_volume
          - script.play_radio
          - script.stop_radio
        show_header_toggle: false
        type: entities
        title: Radio
        id: bcd37a30efe04c2a95126a36081e5241
      - card:
          name: Main TV
          entity: switch.power_main_tv
          type: picture-entity
          tap_action:
            action: toggle
          image: /local/lovelace/tv-switch_1.jpg
        type: 'custom:card-modder'
      - entity: media_player.living_room
        type: media-control
      - entity: media_player.samsung_tv
        type: media-control
      - entity: media_player.family_room_speaker
        type: media-control
  - icon: 'mdi:thermometer'
    background: center / cover no-repeat url("/local/lovelace/background.gif") fixed
    title: Climate
    path: climate
    badges: []
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
      - type: 'custom:mini-graph-card'
        entities:
          - sensor.temperature_158d000170e48e
          - sensor.temperature_158d000170e3ef
      - entities:
          - sensor.humidity_158d000170e48e
          - sensor.humidity_158d000170e3ef
          - sensor.living_room_mold_indicator
        type: 'custom:mini-graph-card'
        title: Outside
        show_header_toggle: false
      - entity: sensor.dark_sky_daily_summary
        type: sensor
      - entities:
          - entity: sensor.bom_temp
          - entity: sensor.bom_humd
          - entity: sensor.bom_wind_sp
          - entity: sensor.bom_wind_bear
        type: entities
        title: BOM
        show_header_toggle: false
      - url: 'https://embed.windy.com/embed2.html?rain,-32.098,116.107,9'
        type: iframe
        aspect_ratio: 150%
  - icon: 'mdi:lightbulb'
    background: center / cover no-repeat url("/local/lovelace/background.gif") fixed
    title: Lights
    path: lights
    badges: []
    theme: darkred
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
      - name: Living Room
        entity: light.gateway_light_286c07f0b826
        type: light
      - name: Bathroom
        entity: light.gateway_light_34ce00813bd1
        type: light
      - type: entities
        entities:
          - entity: sensor.illumination_286c07f0b826
          - entity: sensor.illumination_34ce00813bd1
      - entity: light.desk_led_strip
        type: light
      - entities:
          - input_number.neopixel_animation_speed
        type: entities
        title: Animation Speed
        show_header_toggle: false
      - entities:
          - entity: switch.candles
        type: entities
        title: Switch
        show_header_toggle: false
  - icon: 'mdi:cctv'
    background: center / cover no-repeat url("/local/lovelace/background.gif") fixed
    badges: []
    title: Surveillance
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
      - entity: camera.livingroom6
        type: picture-entity
      - entity: camera.frontgarden134
        type: picture-entity
      - entity: camera.backgarden92
        type: picture-entity
  - icon: 'mdi:shield-home'
    background: center / cover no-repeat url("/local/lovelace/background.gif") fixed
    title: Security
    badges: []
    type: vertical-stack
    panel: false
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
      - card:
          elements:
            - style:
                left: 15%
                top: 88%
                color: white
              entity: alarm_control_panel.ha_alarm
              type: state-icon
            - style:
                left: 32%
                top: 88%
                color: white
              entity: alarm_control_panel.ha_alarm
              type: state-label
              prefix: 'Alarm: '
          type: picture-elements
          image: /local/lovelace/security/alarm.jpg
        type: 'custom:card-modder'
        style:
          border: 'solid 1px rgba(100,100,100,0.3)'
          border-radius: 20px
          overflow: hidden
      - type: vertical-stack
        cards:
          - card:
              elements:
                - style:
                    left: 15%
                    top: 82%
                    color: white
                  entity: binary_sensor.door_window_sensor_158d00019dab6f
                  type: state-icon
                - style:
                    left: 15%
                    top: 92%
                    color: white
                  entity: binary_sensor.door_window_sensor_158d00019dab6f
                  type: state-label
                  prefix: 'Front: '
              type: picture-elements
              image: /local/lovelace/security/door.png
            type: 'custom:card-modder'
            style:
              border: 'solid 1px rgba(100,100,100,0.3)'
              border-radius: 20px
              overflow: hidden
      - type: vertical-stack
        cards:
          - card:
              elements:
                - style:
                    left: 25%
                    top: 82%
                    color: white
                  entity: binary_sensor.motion_sensor_158d0001a2b1f2
                  type: state-icon
                - style:
                    left: 25%
                    top: 92%
                    color: white
                  entity: binary_sensor.motion_sensor_158d0001a2b1f2
                  type: state-label
                  prefix: 'Living: '
              type: picture-elements
              image: /local/lovelace/security/motion.jpg
            type: 'custom:card-modder'
            style:
              border: 'solid 1px rgba(100,100,100,0.3)'
              border-radius: 20px
              overflow: hidden
      - states:
          - arm_home
          - arm_away
          - arm_night
        entity: alarm_control_panel.ha_alarm
        type: alarm-panel
  - icon: 'mdi:cogs'
    background: center / cover no-repeat url("/local/lovelace/background.gif") fixed
    badges: []
    title: System
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
      - type: sensor
        detail: 2
        graph: line
        entity: sensor.cpu_temperature
        name: CPU Temp last 24h
        theme: darkred
      - theme: darkred
        entities:
          - entity: updater.updater
          - entity: sensor.ha_installed_version
        type: entities
        title: Updater
        show_header_toggle: false
      - type: 'custom:mini-graph-card'
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent
      - theme: darkred
        type: entities
        entities:
          - entity: sensor.time
          - entity: sensor.date
          - entity: sensor.season
          - entity: sensor.moon
          - entity: sensor.maceio_time
          - entity: sensor.german_time
      - type: 'custom:tracker-card'
      - entities:
          - entity: input_boolean.zigbee_permit_join
          - entity: timer.zigbee_permit_join
          - entity: sensor.zigbee2mqtt_bridge_state
          - entity: switch.zigbee2mqtt_main_join
          - entity: automation.enable_zigbee_joining
          - entity: automation.disable_zigbee_joining
          - entity: automation.disable_zigbee_joining_by_timer
          - entity: input_select.zigbee2mqtt_log_level
          - entity: automation.zigbee2mqtt_log_level
        type: entities
        title: ZigBee
        show_header_toggle: false
      - entities:
          - entity: sensor.pihole_version
          - entity: sensor.pi_hole_ads_blocked_today
          - entity: sensor.pi_hole_ads_percentage_blocked_today
          - entity: sensor.pi_hole_dns_queries_today
        type: entities
        title: Pi hole
        show_header_toggle: false
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/kalkih/mini-media-player-bundle.js?track=true
    type: module
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /customcards/github/kalkih/mini-graph-card-bundle.js?track=true
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/card-modder.js?track=true
    type: js
