#################################################################
#                                                               #
#                     Packages/Date & Time                      #
#                                                               #
#################################################################


#################################################################
#                                                               #
#                              Sun                              #
#                                                               #
#################################################################

sun:

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Workday              #
#                                                  #
#################################################### 

  - platform: workday
    country: AU
    workdays: [mon, tue, wed, thu, fri]
    
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - Time/Date                #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat
    
####################################################
#                                                  #
#               Sensor - World Clock               #
#                                                  #
####################################################

  - platform: worldclock
    time_zone: America/Maceio
    name: Maceio Time


  - platform: worldclock
    time_zone: Europe/Berlin
    name: German Time

      
####################################################
#                                                  #
#                   Sensor - Moon                  #
#                                                  #
####################################################

  - platform: moon
  
####################################################
#                                                  #
#                  Sensor - Season                 #
#                                                  #
####################################################

  - platform: season
    type: astronomical