#################################################################
#                                                               #
#                    Packages/System Status                     #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Device Tracker                          #
#                                                               #
#################################################################

device_tracker:

####################################################
#                                                  #
#               Device Track - Ping                #
#                                                  #
####################################################

  - platform: ping
    interval_seconds: 30
    hosts:
      core_router: !secret host_core_router
      wifi: !secret host_wifi
      screen: !secret host_screen
      xiaomi_gateway: !secret host_xiaomi_gw_1
      xiaomi_gateway_2: !secret host_xiaomi_gw_2
      printer: !secret host_printer
      samsung_tv: !secret host_samsung_tv
      broadlink: !secret host_broadlink

####################################################
#                                                  #
#              Sensor                              #
#                                                  #
####################################################

sensor:

####################################################
#                                                  #
#              Sensor - Command Line               #
#                                                  #
####################################################

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ (value | multiply(0.001)) | round(1) }}"

####################################################
#                                                  #
#                Sensor - File Size                #
#                                                  #
####################################################

  - platform: filesize
    file_paths:
      - /home/homeassistant/.homeassistant/home-assistant.log

###################################################
## * Special HASS related sensors - Thanks @torn8o
###################################################

  - platform: version
    name: HA Installed Version
    scan_interval: 86400

  - platform: command_line
    name: "HA Uptime"
    command: echo "$(($(date +%s) - $(date -d "$(head -n1 /home/homeassistant/.homeassistant/home-assistant.log | cut -d' ' -f-2)" +%s)))"
    scan_interval: 720
    value_template: >-
      {% set uptime = value | int %}
      {% set seconds = uptime % 60 %}
      {% set minutes = ((uptime % 3600) / 60) | int %}
      {% set hours = ((uptime % 86400) / 3600) | int %}
      {% set days = (uptime / 86400) | int %}
      {%- if days > 0 -%}
        {%- if days == 1 -%}
          1 day
        {%- else -%}
          {{ days }} days
        {%- endif -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if hours > 0 -%}
        {%- if hours == 1 -%}
          1 hour
        {%- else -%}
          {{ hours }} hours
        {%- endif -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if minutes > 0 -%}
        {%- if minutes == 1 -%}
          1 minute
        {%- else -%}
          {{ minutes }} minutes
        {%- endif -%}
      {%- endif -%}

####################################################
#                                                  #
#             Sensor - System Monitor              #
#                                                  #
####################################################

  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot


####################################################
#                                                  #
#                 Sensor - Uptime                  #
#                                                  #
####################################################

  - platform: uptime
    name: Time Online
    unit_of_measurement: hours

#################################################################
#                                                               #
#                          Speed Test                           #
#                                                               #
################################################################# 
  
# speedtestdotnet:
#   server_id: 16329
#   scan_interval:
#     minutes: 30
#   monitored_conditions:
#     - ping
#     - download
#     - upload

#################################################################
#                                                               #
#                         System Health                         #
#                                                               #
################################################################# 

system_health:
       
#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

automation:

## Notify of High Disk Use
  - alias: Disk Use Alarm
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use
      above: 12
    action:
      - service: notify.pushbullet
        data:
          title: 'HA Server'
          message: 'Warning - HA Server Disk Use is {{states.sensor.disk_use.state}}Gb'
          
## Notify of High CPU Usage
  - alias: CPU Use Alarm
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.processor_use
      above: 85
    action:
      - service: notify.pushbullet
        data:
          title: 'HA Server'
          message: 'Warning - HA Server Processor {{states.sensor.processor_use.state}}%'
          
## Notify if CPU Temperature is High
  - alias: CPU Temp Alarm
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      above: 85
    action:
      - service: notify.pushbullet
        data:
          title: 'HA Server'
          message: 'Warning - HA Server CPU Temp is {{states.sensor.cpu_temperature.state}}c'
