#################################################################
#                                                               #
#                        Packages/Lighting                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                         Sensor - Desk                         #
#                                                               #
#################################################################

light:
  - platform: mqtt
    schema: json
    name: "Desk LED Strip"
    state_topic: "home/NanoLED_ha/state/out"
    command_topic: "home/NanoLED_ha/state/in"
    effect: true
    effect_list:
      - "Static"
      - "Blink"
      - "Breath"
      - "Color Wipe"
      - "Color Wipe Inverse"
      - "Color Wipe Reverse"
      - "Color Wipe Reverse Inverse"
      - "Color Wipe Random"
      - "Random Color"
      - "Single Dynamic"
      - "Multi Dynamic"
      - "Rainbow"
      - "Rainbow Cycle"
      - "Scan"
      - "Dual Scan"
      - "Fade"
      - "Theater Chase"
      - "Theater Chase Rainbow"
      - "Running Lights"
      - "Twinkle"
      - "Twinkle Random"
      - "Twinkle Fade"
      - "Twinkle Fade Random"
      - "Sparkle"
      - "Flash Sparkle"
      - "Hyper Sparkle"
      - "Strobe"
      - "Strobe Rainbow"
      - "Multi Strobe"
      - "Blink Rainbow"
      - "Chase White"
      - "Chase Color"
      - "Chase Random"
      - "Chase Rainbow"
      - "Chase Flash"
      - "Chase Flash Random"
      - "Chase Rainbow White"
      - "Chase Blackout"
      - "Chase Blackout Rainbow"
      - "Color Sweep Random"
      - "Running Color"
      - "Running Red Blue"
      - "Running Random"
      - "Larson Scanner"
      - "Comet"
      - "Fireworks"
      - "Fireworks Random"
      - "Merry Christmas"
      - "Fire Flicker"
      - "Fire Flicker (soft)"
      - "Fire Flicker (intense)"
      - "Circus Combustus"
      - "Halloween"
      - "Bicolor Chase"
      - "Tricolor Chase"
      - "ICU"
    brightness: true
    color_temp: false
    rgb: true
    optimistic: true
    qos: 0
    retain: true

#################################################################
#                                                               #
#                          Input Number                         #
#                                                               #
#################################################################

input_number:
  neopixel_animation_speed:
    name: NeoPixel Animation Speed
    initial: 200
    min: 0
    max: 255
    step: 5

#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

automation:
  - alias: NeoPixel Animation Speed Send
    initial_state: true
    hide_entity: false
    trigger:
    - entity_id: input_number.neopixel_animation_speed
      platform: state
    action:
    - data_template:
        payload_template: '{"speed": {{ trigger.to_state.state | int }}}'
        retain: true
        topic: home/NanoLED_ha/state/in
      service: mqtt.publish

  - alias: NeoPixel Animation Speed Receive
    trigger:
    - platform: mqtt
      topic: home/NanoLED_ha/state/out
    action:
    - data_template:
        entity_id: input_number.neopixel_animation_speed
        value: '{{ trigger.payload_json.speed | int }}'
      service: input_number.set_value