#################################################################
#                                                               #
#                        Packages/Lighting                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                         Sensor - Desk                         #
#                                                               #
#################################################################
light:
- platform: mqtt
  name: esp_leds
  state_topic: esp_leds/light/led_1/state
  command_topic: esp_leds/light/led_1/command
  availability_topic: esp_leds/status
  schema: json
  brightness: true